server:
  restart: always
  image: nginx
  volumes:
    - ./server/conf.d:/etc/nginx/conf.d
    - ./app/static:/app/static
  links:
    - web:web
  ports:
    - "9665:80"

web:
  extends:
    file: docker-compose.base.yaml
    service: web
  expose:
    - "8000"
  command: gunicorn app:app -b :8000 --name app --log-level=debug --log-file=- -w 4
